# Project created by QtCreator 2011-04-20T11:01:12

#-------------------------------------------------

QT       += core gui sql xml script network webkit


TARGET = Agila_Faktury
TEMPLATE = app
CONFIG += help
CONFIG += warn_off
RESOURCES += document-templates.qrc
RESOURCES += themes.qrc
SOURCES += main.cpp \
    MainWindow.cpp \
    Other/Application/ApplicationManager.cpp \
    Other/Application/ApplicationInfo.cpp \
    Other/Application/ArgumentsAnalyzer.cpp \
    Database/Database.cpp \
    Database/Model.cpp \
    Database/CacheService.cpp \
    Database/TVModel.cpp \
    Goods/GoodsModel.cpp \
    Goods/Unit.cpp \
    Goods/Goods.cpp \
    Goods/GoodsGroup.cpp \
    Goods/Tax.cpp \
    Goods/Feature.cpp \
    Goods/GoodsDialogView.cpp \
    Goods/GoodsDialogController.cpp \
    Goods/TaxModel.cpp \
    Goods/UnitModel.cpp \
    Goods/GoodsGroupModel.cpp \
    Goods/FeatureModel.cpp \
    Goods/GoodsTVDisplayer.cpp \
    Goods/Price.cpp \
    Goods/GoodsTVModel.cpp \
    Goods/GoodsValidator.cpp \
    Goods/GoodsService.cpp \
    Goods/GoodsCacheService.cpp \
    Contractor/ContractorModel.cpp \
    Contractor/Phone.cpp \
    Contractor/ContractorGroup.cpp \
    Contractor/Contractor.cpp \
    Contractor/SourceOfMember.cpp \
    Contractor/ContractorDialogView.cpp \
    Contractor/ContractorDialogController.cpp \
    Contractor/ContractorGroupModel.cpp \
    Contractor/SOMModel.cpp \
    Contractor/PhoneModel.cpp \
    Contractor/ContractorService.cpp \
    Contractor/PhoneService.cpp \
    Contractor/ContractorTVDisplayer.cpp \
    Contractor/ContractorAdditionalId.cpp \
    Contractor/ContractorAdditionalTypeIdModel.cpp \
    Contractor/ContractorValidator.cpp \
    Contractor/ContractorTVModel.cpp \
    Contractor/ContractorCacheService.cpp \
    Document/MOPModel.cpp \
    Document/MethodOfPayment.cpp \
    Document/Document.cpp \
    Document/SymbolSequence.cpp \
    Document/Symbol.cpp \
    Document/PeopleModel.cpp \
    Document/DocumentPlaceModel.cpp \
    Document/SimpleDocumentInfo.cpp \
    Document/RelatedDocumentModel.cpp \
    Document/DocumentDialog.cpp \
    Document/DocumentPosition.cpp \
    Document/DocumentModel.cpp \
    Document/DocumentNumeratorModel.cpp \
    Document/DocumentNumeratorController.cpp \
    Document/DocumentPositionModel.cpp \
    Document/StoreResultService.cpp \
    Document/DocumentPositionService.cpp \
    Document/DocumentInfo.cpp \
    Document/DocumentInfoModel.cpp \
    Document/DocumentPositionFKModel.cpp \
    Document/DocumentPositionFKService.cpp \
    Document/DocumentValidator.cpp \
    Document/DocumentService.cpp \
    Document/DocumentTVDisplayer.cpp \
    Document/DocumentTVModel.cpp \
    Document/DocumentManager.cpp \
    Document/DocumentController.cpp \
    Document/SaleDocument/DocumentFKView.cpp \
    Document/SaleDocument/DocumentFKController.cpp \
    Document/SaleDocument/InvoiceModel.cpp \
    Document/SaleDocument/Invoice.cpp \
    Document/SaleDocument/InvoiceController.cpp \
    Document/SaleDocument/InvoiceView.cpp \
    Document/SaleDocument/DocumentFKModel.cpp \
    Document/SaleDocument/SaleDocumentTVModel.cpp \
    Document/SaleDocument/DocumentFK.cpp \
    Document/SaleDocument/DocumentZALService.cpp \
    Document/SaleDocument/DocumentZALModel.cpp \
    Document/SaleDocument/DocumentZAL.cpp \
    Document/SaleDocument/InvoiceService.cpp \
    Document/SaleDocument/DocumentFKService.cpp \
    Document/SaleDocument/InvoiceManager.cpp \
    Document/SaleDocument/DocumentFKManager.cpp \
    Document/SaleDocument/SaleManager.cpp \
    Document/SaleDocument/SaleView.cpp \
    Document/SaleDocument/SaleController.cpp \
    Document/SaleDocument/DocumentPAView.cpp \
    Document/SaleDocument/DocumentPAController.cpp \
    Document/SaleDocument/DocumentPAManager.cpp \
    Document/SaleDocument/DocumentPAPolicy.cpp \
    Document/SaleDocument/DocumentFMView.cpp \
    Document/SaleDocument/DocumentFMController.cpp \
    Document/SaleDocument/DocumentFMManager.cpp \
    Document/SaleDocument/DocumentZALManager.cpp \
    Document/SaleDocument/DocumentZALPolicy.cpp \
    Document/StoreDocument/StoreDocumentTVModel.cpp \
    Document/StoreDocument/DocumentPZ.cpp \
    Document/StoreDocument/DocumentPZView.cpp \
    Document/StoreDocument/DocumentPZController.cpp \
    Document/StoreDocument/DocumentWZController.cpp \
    Document/StoreDocument/DocumentWZ.cpp \
    Document/StoreDocument/DocumentWZView.cpp \
    Document/StoreDocument/StoreDocumentController.cpp \
    Document/StoreDocument/DocumentPZModel.cpp \
    Document/StoreDocument/DocumentWZModel.cpp \
    Document/StoreDocument/DepartmentModel.cpp \
    Document/StoreDocument/DocumentPZService.cpp \
    Document/StoreDocument/DocumentWZService.cpp \
    Document/StoreDocument/TransportModel.cpp \
    Document/StoreDocument/StoreDocumentView.cpp \
    Document/StoreDocument/StoreDocumentManager.cpp \
    Document/StoreDocument/DocumentPZManager.cpp \
    Document/StoreDocument/DocumentPZPolicy.cpp \
    Document/StoreDocument/StoreDocument.cpp \
    Document/StoreDocument/DocumentWZManager.cpp \
    Document/StoreDocument/DocumentWZPolicy.cpp \
    Document/StoreDocument/StorageController.cpp \
    Document/StoreDocument/StorageView.cpp \
    Document/StoreDocument/StorageModel.cpp \
    Document/StoreDocument/StorageManager.cpp \
    Document/StoreDocument/StoragePolicy.cpp \
    Document/StoreDocument/StorageService.cpp \
    Document/CashDocument/CashDocumentTVModel.cpp \
    Document/CashDocument/CashDocumentValidator.cpp \
    Document/OrderDocument/OrderModel.cpp \
    Document/OrderDocument/Order.cpp \
    Document/OrderDocument/OrderDocumentTVModel.cpp \
    Document/OrderDocument/OrderService.cpp \
    Document/OrderDocument/OrderManager.cpp \
    Document/OrderDocument/OrderView.cpp \
    Document/OrderDocument/OrderController.cpp \
    Document/PurchaseDocument/PurchaseDocumentTVModel.cpp \
    Document/PurchaseDocument/DocumentNKModel.cpp \
    Document/PurchaseDocument/DocumentNKView.cpp \
    Document/PurchaseDocument/DocumentNKController.cpp \
    Document/PurchaseDocument/DocumentFZK.cpp \
    Document/PurchaseDocument/PurchaseInvoice.cpp \
    Document/PurchaseDocument/PurchaseInvoiceModel.cpp \
    Document/PurchaseDocument/PurchaseInvoiceService.cpp \
    Document/PurchaseDocument/DocumentFZKModel.cpp \
    Document/PurchaseDocument/DocumentFZKService.cpp \
    Document/PurchaseDocument/DocumentNKService.cpp \
    Document/PurchaseDocument/DocumentNK.cpp \
    Document/PurchaseDocument/PurchaseInvoiceView.cpp \
    Document/PurchaseDocument/PurchaseInvoiceController.cpp \
    Document/PurchaseDocument/PurchasePolicy.cpp \
    Document/PurchaseDocument/PurchaseController.cpp \
    Document/PurchaseDocument/PurchaseManager.cpp \
    Document/PurchaseDocument/DocumentRRView.cpp \
    Document/PurchaseDocument/DocumentRRController.cpp \
    Document/PurchaseDocument/DocumentFZKView.cpp \
    Document/PurchaseDocument/DocumentFZKController.cpp \
    Document/PurchaseDocument/DocumentFZKPolicy.cpp\
    Document/PurchaseDocument/DocumentFZKManager.cpp \
    Settings/SettingsModel.cpp \
    Settings/SettingsPanelView.cpp \
    Settings/SettingsPanelController.cpp \
    Settings/SettingsAbstractItemView.cpp \
    Settings/SettingsAbstractItemController.cpp \
    Settings/ContractorsSettings/SettingsContractorGroupsView.cpp \
    Settings/ContractorsSettings/SettingsContractorGroupsController.cpp \
    Settings/GoodsSettings/SettingsUnitsView.cpp \
    Settings/GoodsSettings/SettingsTaxesController.cpp \
    Settings/GoodsSettings/SettingsTaxesView.cpp \
    Settings/GoodsSettings/SettingsUnitsController.cpp \
    Settings/GoodsSettings/SettingsGoodGroupsView.cpp \
    Settings/GoodsSettings/SettingsGoodGroupsController.cpp \
    Settings/GoodsSettings/SettingsFeaturesController.cpp \
    Settings/GoodsSettings/SettingsFeaturesView.cpp \
    Settings/GoodsSettings/SettingsMassTaxesChangeView.cpp \
    Settings/GoodsSettings/SettingsMassTaxesChangeController.cpp \
    Settings/OtherSettings/SettingsOwnerView.cpp \
    Settings/OtherSettings/SettingsOwnerController.cpp \
    Settings/DocumentsSettings/SettingsMOPView.cpp \
    Settings/DocumentsSettings/SettingsMOPController.cpp \
    Settings/DocumentsSettings/SettingsDocumentTextView.cpp \
    Settings/DocumentsSettings/SettingsDocumentNumberingView.cpp \
    Settings/DocumentsSettings/SettingsDocumentNumberingController.cpp \
    Settings/DocumentsSettings/SettingsDocumentTextController.cpp \
    Settings/DocumentsSettings/SettingsDefaultDocPlaceView.cpp \
    Settings/DocumentsSettings/SettingsDefaultDocPlaceController.cpp \
    Settings/StoreSettings/SettingsMagazineView.cpp \
    Settings/StoreSettings/SettingsMagazineController.cpp \
    Settings/StoreSettings/SettingsMagazineItemView.cpp \
    Settings/StoreSettings/SettingsMagazineItemController.cpp \
    Settings/OtherSettings/SettingsPrintController.cpp \
    Settings/OtherSettings/SettingsPrintView.cpp \
    Settings/OtherSettings/SettingsUserView.cpp \
    Settings/OtherSettings/SettingsUserController.cpp \
    Settings/OtherSettings/SettingsOutlookView.cpp \
    Settings/OtherSettings/SettingsOutlookController.cpp\
    Settings/StoreSettings/WarehouseDialogController.cpp \
    Settings/StoreSettings/WarehouseDialogView.cpp \
    Other/Owner/Owner.cpp \
    Other/Owner/OwnerModel.cpp \
    Other/Owner/OwnerService.cpp \
    Other/Owner/OwnerCacheService.cpp \
    Other/Warehouse/Warehouse.cpp \
    Other/SimpleStructure.cpp \
    Other/TVDisplayer.cpp \
    Other/Exceptions/SQLException.cpp \
    Other/Exceptions/Exception.cpp \
    Other/Exceptions/NoHttpResponseException.cpp \
    Other/Exceptions/NoLicenseKeyException.cpp \
    Other/Validator.cpp \
    Other/Service.cpp \
    Other/TableStateManager.cpp \
    Other/ITableStateManager.cpp \
    Other/SimpleStringStructure.cpp \
    Other/SimpleCrypt.cpp \
    Other/Network/HttpRequester.cpp \
    Other/Network/NetworkHelper.cpp \
    Other/Network/JsonObject.cpp \
    SelectionWindows/SelectContractorView.cpp \
    SelectionWindows/SelectContractorController.cpp \
    SelectionWindows/SelectGoodController.cpp \
    SelectionWindows/SelectGoodView.cpp \
    SelectionWindows/SelectionNumberOfGoodsController.cpp \
    SelectionWindows/SelectionNumberOfGoodsView.cpp \
    SelectionWindows/SelectInvoiceController.cpp \
    SelectionWindows/SelectInvoiceView.cpp \
    SelectionWindows/SelectOrderController.cpp \
    Tools/Archiver/ArchiverDialogController.cpp \
    Tools/Archiver/ArchiverDialogView.cpp \
    Tools/Archiver/ArchiverService.cpp \
    Tools/Archiver/ArchiverReminder.cpp \
    Tools/Archiver/ArchiverAutoRemover.cpp \
    Tools/Archiver/ArchiverSettings.cpp \
    Tools/TaxChanger/TaxChangerModel.cpp \
    Tools/Print/PrintEngine.cpp \
    Tools/Print/PrintManager.cpp \
    Tools/Print/NumberToWords.cpp \
    Tools/Exporter/CsvMapWriter.cpp \
    Tools/Exporter/CsvExporter.cpp \
    Tools/Exporter/CsvGoodsExporter.cpp \
    Tools/Exporter/CsvGoodsExporterDialogController.cpp \
    Tools/Exporter/CsvContractorExporter.cpp \
    Tools/Exporter/CsvContractorExporterDialogController.cpp \
    Tools/Exporter/CsvExporterDialogController.cpp \
    Tools/Exporter/CsvExporterDialogView.cpp \
    Tools/Updater/UpdateInfo.cpp \
    Tools/Updater/Updater.cpp \
    Tools/Updater/UpdateHelper.cpp \
    Components/TableView.cpp \
    Components/InsertTextDialog.cpp \
    Components/MessageBox.cpp \
    Components/CalendarWidget.cpp \
    Components/DateEdit.cpp \
    Components/FileInfo.cpp \
    Components/Button.cpp \
    Components/ButtonStruct.cpp \
    Components/ButtonBox.cpp \
    User/UserModel.cpp \
    User/User.cpp \
    User/UserService.cpp \
    User/LoggingSystemView.cpp \
    User/LoggingSystemController.cpp \
    Report/Inventory/CurrentInventoryDialogController.cpp \
    Report/Inventory/CurrentInventoryDialogView.cpp \
    Report/Inventory/CurrentInventoryGroupsDialogController.cpp \
    Report/Inventory/CurrentInventoryGroupsDialogView.cpp \
    Report/Inventory/CurrentInventoryGroupsTVModel.cpp \
    Report/Inventory/CurrentInventoryGroupsTVDisplayer.cpp \
    Report/Inventory/CurrentInventoryTVDisplayer.cpp \
    Report/Inventory/CurrentInventoryTVModel.cpp \
    Report/Inventory/InventoryDialogView.cpp \
    Report/ReportDialogController.cpp \
    Report/Order/UnrealizedOrderDialogController.cpp \
    Report/Order/UnrealizedOrderDialogView.cpp \
    Report/Order/UnrealizedOrderTVModel.cpp \
    Report/Goods/MissingGoodsDialogController.cpp \
    Report/Goods/MissingGoodsDialogView.cpp \
    Report/Goods/ReportGoodsTVModel.cpp \
    Report/Order/UnrealizedOrderTVDisplayer.cpp \
    Report/Goods/ReportGoodsTVDisplayer.cpp \
    Report/Goods/EndingGoodsDialogController.cpp \
    Report/Goods/EndingGoodsDialogView.cpp \
    Report/Goods/OrderedGoodsDialogController.cpp \
    Report/Goods/OrderedGoodsDialogView.cpp \
    Report/Goods/OrderedGoodsTVModel.cpp \
    Report/Goods/OrderedGoodsTVDisplayer.cpp \
    Report/Goods/TopGoodsTVModel.cpp \
    Report/Goods/TopGoodsDialogController.cpp \
    Report/Goods/TopGoodsDialogView.cpp \
    Report/Goods/TopGoodsTVDisplayer.cpp \
    Report/Unpaid/UnpaidSaleDocumentDialogController.cpp \
    Report/Unpaid/UnpaidDocumentDialogView.cpp \
    Report/ReportDialogView.cpp \
    Report/Unpaid/UnpaidDocumentTVDisplayer.cpp \
    Report/Report.cpp \
    Report/Unpaid/UnpaidPurchaseDocumentDialogController.cpp \
    Report/Unpaid/UnpaidDocumentDialogController.cpp \
    Report/Unpaid/UnpaidDocumentTVModel.cpp \
    Report/Contractor/TopContractorsTVModel.cpp \
    Report/Contractor/TopContractorsDialogController.cpp \
    Report/Contractor/TopContractorsDialogView.cpp \
    Report/Contractor/TopContractorsTVDisplayer.cpp \
    Main/MainTab.cpp \
    Main/MainTabItem.cpp \
    Main/MainTabGoodsItem.cpp \
    Main/MainTabContractorsItem.cpp \
    Main/MainTabPurchaseItem.cpp \
    Main/MainTabOrderItem.cpp \
    Main/MainTabOthersItem.cpp \
    Main/MainTabReportsItem.cpp \
    Main/MainTabSaleItem.cpp \
    Main/MainTabStoreItem.cpp \
    Main/MainMenu.cpp \
    Main/MainTabGoodsItemController.cpp \
    Main/MainTabOrderItemController.cpp \
    Main/MainTabPurchaseItemController.cpp \
    Main/MainTabReportsItemController.cpp \
    Main/MainTabSaleItemController.cpp \
    Main/MainTabStoreItemController.cpp \
    Main/MainMenuController.cpp \
    Main/MainTabOthersItemController.cpp \
    Main/MainTabContractorsItemController.cpp \
    Main/MainStoreComboBox.cpp \
    Main/MainStoreComboBoxController.cpp \
    Main/MainTabCashItem.cpp \
    Main/MainTabCashItemController.cpp \
    Main/MainTabDocumentFilterWidget.cpp \
    Main/MainTabDocumentItemController.cpp \
    Main/MainTabDocumentItem.cpp \
    Menu/Menu.cpp \
    Menu/TableViewStandardMenu.cpp \
    Menu/MenuSale.cpp \
    Menu/MenuStore.cpp \
    Menu/MenuPurchase.cpp \
    Menu/MenuCash.cpp \
    Menu/MenuOrder.cpp \
    Menu/TableViewExtendedMenu.cpp \
    Document/SaleDocument/InvoicePolicy.cpp \
    Document/DocumentView.cpp \
    Document/OrderDocument/OrderPolicy.cpp \
    Document/SaleDocument/DocumentFKPolicy.cpp \
    Tools/Help/HelpDialogView.cpp \
    Settings/SettingsTVModel.cpp \
    SelectionWindows/SelectVisibleColumns.cpp \
    Components/ProgressBarDialog.cpp \
    Settings/StoreSettings/SettingsTransportView.cpp \
    Settings/StoreSettings/SettingsTransportController.cpp \
    Other/Warehouse/WarehouseModel.cpp \
    Other/Warehouse/WarehouseService.cpp \
    Document/SaleDocument/DocumentZALController.cpp \
    Document/SaleDocument/DocumentZALView.cpp\
    Goods/GoodsRemoveConfirmativeDialog.cpp \
    Main/MainTabItemController.cpp \
    Components/ButtonsList.cpp \
    Components/AddGroup.cpp \
    Tools/Help/HelpBrowser.cpp \
    Other/Logger.cpp \
    Components/Money.cpp \
    Other/Application/ModuleManager.cpp \
    Tools/Print/PrintDialogView.cpp \
    Tools/Print/PrintDialogController.cpp \
    Tools/Print/DocumentServices.cpp \
    Tools/Print/PrintPreviewDialog.cpp \
    Tools/Updater/UpdateChecker.cpp \
    Other/BlueBraces.cpp \
    Other/OtherService.cpp \
    Other/OtherModel.cpp \
    Other/Preferences/SettingsPreferencesModel.cpp \
    Other/Preferences/SettingsPreference.cpp \
    Other/Preferences/SettingsPreferencesService.cpp \
    Settings/GoodsSettings/SettingsPricesView.cpp \
    Settings/GoodsSettings/SettingsPricesController.cpp \
    Settings/DocumentsSettings/SettingsPriceSelectionView.cpp \
    Settings/DocumentsSettings/SettingsPriceSelectionController.cpp \
    Components/ToolButton.cpp \
    Main/MainTabPriceItem.cpp \
    Main/MainTabPriceItemController.cpp \
    Document/PriceDocument/PriceListView.cpp \
    Document/PriceDocument/PriceListController.cpp \
    Document/PriceDocument/PriceListModel.cpp \
    Document/PriceDocument/PriceList.cpp \
    Tools/Print/PrintSaleDocumentController.cpp \
    Tools/Print/PrintStoreDocumentController.cpp \
    Tools/Print/PrintCashDocumentController.cpp \
    Tools/Print/PrintPurchaseDocumentController.cpp \
    Tools/Print/PrintSaleDocumentManager.cpp \
    Tools/Print/PrintStoreDocumentManager.cpp \
    Tools/Print/PrintPurchaseDocumentManager.cpp \
    Tools/Print/HtmlStringReplacer.cpp \
    Tools/Print/PrintOrderDocumentController.cpp \
    Tools/Print/PrintOrderDocumentManager.cpp\
    Document/PriceDocument/PriceListService.cpp \
    Document/PriceDocument/PriceDocumentTVModel.cpp \
    Document/PriceDocument/PriceGoodSelectorController.cpp \
    Goods/GoodsTVStandardItemModel.cpp \
    Goods/GoodsFilters.cpp \
    Document/PriceDocument/PriceDocumentsValidator.cpp \
    Application.cpp \
    Document/PriceDocument/PriceDocumentView.cpp \
    Document/PriceDocument/OfferView.cpp \
    Document/PriceDocument/OfferController.cpp \
    Document/PriceDocument/OfferService.cpp \
    Document/PriceDocument/PriceDocumentController.cpp \
    Other/Application/Style.cpp \
    Document/PriceDocument/OfferModel.cpp \
    Document/CashDocument/CashDocumentService.cpp \
    Document/CashDocument/CashDocumentView.cpp \
    Document/CashDocument/CashDocumentController.cpp \
    Document/CashDocument/CashDocumentModel.cpp \
    Document/CashDocument/CashDocument.cpp


HEADERS  += MainWindow.h \
    Other/Application/ApplicationManager.h \
    Other/Application/ApplicationInfo.h \
    Other/Application/ArgumentsAnalyzer.h \
    Database/Database.h \
    Database/Model.h \
    Database/CacheService.h \
    Database/TVModel.h \
    Goods/GoodsModel.h \
    Goods/Unit.h \
    Goods/Goods.h \
    Goods/GoodsGroup.h \
    Goods/Tax.h \
    Goods/Feature.h \
    Goods/GoodsDialogView.h \
    Goods/GoodsDialogController.h \
    Goods/TaxModel.h \
    Goods/UnitModel.h \
    Goods/GoodsGroupModel.h \
    Goods/FeatureModel.h \
    Goods/GoodsTVDisplayer.h \
    Goods/Price.h \
    Goods/GoodsTVModel.h \
    Goods/GoodsValidator.h \
    Goods/GoodsService.h \
    Goods/GoodsCacheService.h \
    Contractor/ContractorModel.h \
    Contractor/Phone.h \
    Contractor/ContractorGroup.h \
    Contractor/Contractor.h \
    Contractor/SourceOfMember.h \
    Contractor/ContractorDialogView.h \
    Contractor/ContractorDialogController.h \
    Contractor/PhoneModel.h \
    Contractor/ContractorGroupModel.h \
    Contractor/SOMModel.h \
    Contractor/PhoneService.h \
    Contractor/ContractorService.h \
    Contractor/ContractorTVDisplayer.h \
    Contractor/ContractorAdditionalId.h \
    Contractor/ContractorAdditionalTypeIdModel.h \
    Contractor/ContractorValidator.h \
    Contractor/ContractorCacheService.h \
    Contractor/ContractorTVModel.h \
    Document/MethodOfPayment.h \
    Document/Document.h \
    Document/SymbolSequence.h \
    Document/Symbol.h \
    Document/DocumentDialog.h \
    Document/DocumentPosition.h \
    Document/DocumentModel.h \
    Document/DocumentNumeratorModel.h \
    Document/DocumentNumeratorController.h \
    Document/MOPModel.h \
    Document/DocumentPositionModel.h \
    Document/StoreResultService.h \
    Document/DocumentPositionService.h \
    Document/DocumentInfo.h \
    Document/DocumentInfoModel.h \
    Document/PeopleModel.h \
    Document/DocumentPlaceModel.h \
    Document/SimpleDocumentInfo.h \
    Document/RelatedDocumentModel.h \
    Document/SaleDocument/InvoiceModel.h \
    Document/SaleDocument/Invoice.h \
    Document/SaleDocument/InvoiceController.h \
    Document/SaleDocument/DocumentFKModel.h \
    Document/SaleDocument/SaleDocumentTVModel.h \
    Document/SaleDocument/DocumentFKView.h \
    Document/SaleDocument/DocumentFKController.h \
    Document/SaleDocument/DocumentFK.h \
    Document/SaleDocument/InvoiceView.h \
    Document/SaleDocument/DocumentZALService.h \
    Document/SaleDocument/DocumentZALModel.h \
    Document/StoreDocument/StoreDocumentTVModel.h \
    Document/StoreDocument/DocumentPZ.h \
    Document/StoreDocument/DocumentPZView.h \
    Document/StoreDocument/DocumentPZController.h \
    Document/StoreDocument/DocumentWZController.h \
    Document/StoreDocument/DocumentWZ.h \
    Document/StoreDocument/DocumentWZView.h \
    Document/StoreDocument/StoreDocumentController.h \
    Document/StoreDocument/DocumentPZModel.h \
    Document/StoreDocument/DocumentWZModel.h \
    Document/StoreDocument/DepartmentModel.h \
    Document/PurchaseDocument/DocumentNK.h \
    Document/OrderDocument/OrderModel.h \
    Document/OrderDocument/Order.h \
    Document/OrderDocument/OrderDocumentTVModel.h \
    Document/CashDocument/CashDocumentTVModel.h \
    Document/CashDocument/CashDocumentValidator.h \
    Document/PurchaseDocument/PurchaseDocumentTVModel.h \
    Document/PurchaseDocument/DocumentNKModel.h \
    Document/PurchaseDocument/DocumentNKView.h \
    Document/PurchaseDocument/DocumentNKController.h \
    Document/PurchaseDocument/DocumentFZK.h \
    Document/PurchaseDocument/PurchaseInvoice.h \
    Document/PurchaseDocument/PurchaseInvoiceModel.h \
    Document/PurchaseDocument/PurchaseInvoiceService.h \
    Document/PurchaseDocument/DocumentFZKModel.h \
    Document/PurchaseDocument/DocumentFZKService.h \
    Settings/SettingsModel.h \
    Settings/SettingsPanelView.h \
    Settings/SettingsPanelController.h\
    Settings/SettingsAbstractItemView.h\
    Settings/SettingsAbstractItemController.h\
    Settings/ContractorsSettings/SettingsContractorGroupsView.h \
    Settings/ContractorsSettings/SettingsContractorGroupsController.h \
    Settings/GoodsSettings/SettingsUnitsView.h \
    Settings/GoodsSettings/SettingsTaxesController.h \
    Settings/GoodsSettings/SettingsTaxesView.h \
    Settings/GoodsSettings/SettingsUnitsController.h \
    Settings/GoodsSettings/SettingsGoodGroupsView.h \
    Settings/GoodsSettings/SettingsGoodGroupsController.h \
    Settings/GoodsSettings/SettingsFeaturesController.h \
    Settings/GoodsSettings/SettingsFeaturesView.h \
    Settings/GoodsSettings/SettingsMassTaxesChangeView.h \
    Settings/GoodsSettings/SettingsMassTaxesChangeController.h \
    Settings/OtherSettings/SettingsOwnerView.h \
    Settings/OtherSettings/SettingsOwnerController.h \
    Settings/DocumentsSettings/SettingsMOPView.h \
    Settings/DocumentsSettings/SettingsMOPController.h \
    Settings/DocumentsSettings/SettingsDocumentTextView.h \
    Settings/DocumentsSettings/SettingsDocumentNumberingView.h \
    Settings/DocumentsSettings/SettingsDocumentNumberingController.h \
    Settings/DocumentsSettings/SettingsDocumentTextController.h \
    Settings/DocumentsSettings/SettingsDefaultDocPlaceView.h \
    Settings/DocumentsSettings/SettingsDefaultDocPlaceController.h \
    Settings/StoreSettings/SettingsMagazineView.h\
    Settings/StoreSettings/SettingsMagazineController.h\
    Settings/StoreSettings/SettingsMagazineItemView.h\
    Settings/StoreSettings/SettingsMagazineItemController.h\
    Settings/OtherSettings/SettingsPrintController.h \
    Settings/OtherSettings/SettingsPrintView.h \
    Settings/OtherSettings/SettingsUserView.h \
    Settings/OtherSettings/SettingsUserController.h \
    Other/Owner/Owner.h \
    Other/Store.h \
    Other/SimpleStructure.h \
    Other/TVDisplayer.h \
    Other/Validator.h \
    Other/Service.h \
    Other/SimpleStringStructure.h \
    Other/Exceptions/SQLException.h \
    Other/Exceptions/Exception.h \
    Other/Owner/OwnerModel.h \
    Other/Owner/OwnerService.h \
    Other/Owner/OwnerCacheService.h \
    Other/Network/JsonObject.h \
    Tools/Archiver/ArchiverDialogController.h \
    Tools/Archiver/ArchiverDialogView.h \
    Tools/Archiver/ArchiverService.h \
    Tools/Archiver/ArchiverReminder.h \
    Tools/Archiver/ArchiverAutoRemover.h \
    Tools/Archiver/ArchiverSettings.h \
    Tools/TaxChanger/TaxChangerModel.h \
    Tools/Print/PrintEngine.h \
    Tools/Print/PrintManager.h \
    Tools/Print/NumberToWords.h \
    Tools/Exporter/CsvMapWriter.h \
    Tools/Exporter/CsvExporter.h \
    Tools/Exporter/CsvGoodsExporter.h \
    Tools/Exporter/CsvGoodsExporterDialogController.h \
    Tools/Exporter/CsvGoodsExporterDialogView.h \
    Tools/Exporter/CsvContractorExporter.h \
    Tools/Exporter/CsvContractorExporterDialogController.h \
    Tools/Exporter/CsvContractorExporterDialogView.h \
    Tools/Exporter/CsvExporterDialogController.h \
    Tools/Exporter/CsvExporterDialogView.h \
    Tools/Updater/UpdateInfo.h \
    Tools/Updater/Updater.h \
    Tools/Updater/UpdateHelper.h \
    Tools/Updater/UpdateChecker.h \
    SelectionWindows/SelectContractorView.h \
    SelectionWindows/SelectContractorController.h \
    SelectionWindows/SelectGoodController.h \
    SelectionWindows/SelectGoodView.h \
    SelectionWindows/SelectionNumberOfGoodsController.h \
    SelectionWindows/SelectionNumberOfGoodsView.h \
    SelectionWindows/SelectInvoiceController.h \
    SelectionWindows/SelectInvoiceView.h \
    SelectionWindows/SelectOrderController.h \
    Components/TableView.h \
    Components/InsertTextDialog.h \
    Components/MessageBox.h \
    Components/CalendarWidget.h \
    Components/DateEdit.h \
    Components/FileInfo.h \
    Components/ButtonStruct.h \
    Components/Button.h \
    Components/ButtonBox.h \
    Document/StoreDocument/TransportModel.h \
    User/UserModel.h \
    User/User.h \
    User/UserService.h \
    User/LoggingSystemController.h \
    Document/DocumentValidator.h \
    Document/SaleDocument/DocumentZAL.h \
    Document/SaleDocument/InvoiceService.h \
    Document/DocumentService.h \
    Document/SaleDocument/DocumentFKService.h \
    Document/DocumentPositionFKModel.h \
    Document/DocumentPositionFKService.h \
    Document/StoreDocument/DocumentPZService.h \
    Document/StoreDocument/DocumentWZService.h \
    Document/OrderDocument/OrderService.h \
    Document/PurchaseDocument/DocumentNKService.h \
    Report/Inventory/CurrentInventoryDialogView.h \
    Report/Inventory/CurrentInventoryDialogController.h \
    Report/Inventory/CurrentInventoryGroupsDialogController.h \
    Report/Inventory/CurrentInventoryGroupsDialogView.h \
    Report/Inventory/CurrentInventoryGroupsTVModel.h \
    Report/Inventory/CurrentInventoryGroupsTVDisplayer.h \
    Report/Inventory/CurrentInventoryTVModel.h \
    Report/Inventory/CurrentInventoryTVDisplayer.h \
    Report/Inventory/InventoryDialogView.h \
    Report/ReportDialogController.h \
    Report/Order/UnrealizedOrderDialogController.h \
    Report/Order/UnrealizedOrderDialogView.h \
    Report/Order/UnrealizedOrderTVModel.h \
    Report/Goods/MissingGoodsDialogController.h \
    Report/Goods/MissingGoodsDialogView.h \
    Report/Goods/ReportGoodsTVModel.h \
    Report/Order/UnrealizedOrderTVDisplayer.h \
    Report/Goods/ReportGoodsTVDisplayer.h \
    Report/Goods/EndingGoodsDialogController.h \
    Report/Goods/EndingGoodsDialogView.h \
    Report/Goods/OrderedGoodsDialogController.h \
    Report/Goods/OrderedGoodsDialogView.h \
    Report/Goods/OrderedGoodsTVModel.h \
    Report/Goods/OrderedGoodsTVDisplayer.h \
    Report/Goods/TopGoodsTVModel.h \
    Report/Goods/TopGoodsDialogController.h \
    Report/Goods/TopGoodsDialogView.h \
    Report/Goods/TopGoodsTVDisplayer.h \
    Report/Unpaid/UnpaidSaleDocumentDialogController.h \
    Report/Unpaid/UnpaidDocumentDialogView.h \
    Report/ReportDialogView.h \
    Report/Unpaid/UnpaidDocumentTVDisplayer.h \
    Report/Report.h \
    Report/Unpaid/UnpaidPurchaseDocumentDialogController.h \
    Report/Unpaid/UnpaidDocumentDialogController.h \
    Report/Unpaid/UnpaidDocumentTVModel.h \
    Report/Contractor/TopContractorsTVModel.h \
    Report/Contractor/TopContractorsDialogController.h \
    Report/Contractor/TopContractorsDialogView.h \
    Report/Contractor/TopContractorsTVDisplayer.h \
    Main/MainTab.h \
    Main/MainTabItem.h \
    Main/MainTabGoodsItem.h \
    Main/MainTabContractorsItem.h \
    Main/MainTabPurchaseItem.h \
    Main/MainTabOrderItem.h \
    Main/MainTabOthersItem.h \
    Main/MainTabReportsItem.h \
    Main/MainTabSaleItem.h \
    Main/MainTabStoreItem.h \
    Main/MainMenu.h \
    Main/MainTabGoodsItemController.h \
    Main/MainTabOrderItemController.h \
    Main/MainTabPurchaseItemController.h \
    Main/MainTabReportsItemController.h \
    Main/MainTabSaleItemController.h \
    Main/MainTabStoreItemController.h \
    Main/MainMenuController.h \
    Main/MainTabOthersItemController.h \
    Main/MainTabContractorsItemController.h \
    Main/MainTabGoodsItemController.h \
    Main/MainTabOrderItemController.h \
    Main/MainTabPurchaseItemController.h \
    Main/MainTabReportsItemController.h \
    Main/MainTabSaleItemController.h \
    Main/MainTabStoreItemController.h \
    Main/MainStoreComboBox.h \
    Main/MainStoreComboBoxController.h \
    Main/MainTabCashItem.h \
    Main/MainTabCashItemController.h \
    Main/MainTabDocumentFilterWidget.h \
    Main/MainTabDocumentItemController.h \
    Main/MainTabDocumentItem.h \
    Document/SaleDocument/InvoiceManager.h \
    Document/SaleDocument/DocumentFKManager.h \
    Document/DocumentTVDisplayer.h \
    Document/DocumentTVModel.h \
    Document/SaleDocument/SaleManager.h \
    Document/DocumentManager.h \
    Menu/Menu.h \
    Menu/TableViewStandardMenu.h \
    Menu/MenuSale.h \
    Menu/MenuStore.h \
    Menu/MenuPurchase.h \
    Menu/MenuCash.h \
    Menu/MenuOrder.h \
    Menu/TableViewExtendedMenu.h \
    Document/DocumentController.h \
    Document/SaleDocument/InvoicePolicy.h \
    Document/DocumentView.h \
    Document/SaleDocument/SaleView.h \
    Document/SaleDocument/SaleController.h \
    Document/SaleDocument/DocumentPAView.h \
    Document/SaleDocument/DocumentPAController.h \
    Document/SaleDocument/DocumentPAManager.h \
    Document/SaleDocument/DocumentPAPolicy.h \
    Document/SaleDocument/DocumentFMView.h \
    Document/SaleDocument/DocumentFMController.h \
    Document/SaleDocument/DocumentFMManager.h \
    Document/PurchaseDocument/PurchaseInvoiceView.h \
    Document/PurchaseDocument/PurchaseInvoiceController.h \
    Document/PurchaseDocument/PurchasePolicy.h \
    Document/PurchaseDocument/PurchaseController.h \
    Document/PurchaseDocument/PurchaseManager.h \
    Document/PurchaseDocument/DocumentRRView.h \
    Document/PurchaseDocument/DocumentRRController.h \
    Document/PurchaseDocument/DocumentFZKView.h \
    Document/PurchaseDocument/DocumentFZKController.h \
    Document/OrderDocument/OrderManager.h \
    Document/OrderDocument/OrderView.h \
    Document/OrderDocument/OrderController.h \
    Other/TableStateManager.h \
    Other/ITableStateManager.h \
    Document/OrderDocument/OrderPolicy.h \
    Document/SaleDocument/DocumentFKPolicy.h \
    Document/PurchaseDocument/DocumentFZKPolicy.h\
    Document/PurchaseDocument/DocumentFZKManager.h \
    Document/StoreDocument/StoreDocumentView.h \
    Document/StoreDocument/StoreDocumentManager.h \
    Document/StoreDocument/DocumentPZManager.h \
    Document/StoreDocument/DocumentPZPolicy.h \
    Document/StoreDocument/StoreDocument.h \
    Document/StoreDocument/DocumentWZManager.h \
    Document/StoreDocument/DocumentWZPolicy.h \
    Document/StoreDocument/StorageController.h \
    Document/StoreDocument/StorageView.h \
    Document/StoreDocument/StorageModel.h \
    Document/StoreDocument/StorageManager.h \
    Document/StoreDocument/StoragePolicy.h \
    Document/StoreDocument/StorageService.h\
    Tools/Help/HelpDialogView.h \
    Tools/Help/HelpBrowser.h \
    Settings/SettingsTVModel.h \
    SelectionWindows/SelectVisibleColumns.h \
    Other/Warehouse/WarehouseModel.h \
    Other/Warehouse/Warehouse.h \
    User/LoggingSystemView.h \
    Components/ProgressBarDialog.h \
    Settings/StoreSettings/WarehouseDialogController.h \
    Settings/StoreSettings/WarehouseDialogView.h \
    Settings/StoreSettings/SettingsTransportView.h \
    Settings/StoreSettings/SettingsTransportController.h \
    Other/Warehouse/WarehouseService.h \
    Document/SaleDocument/DocumentZALController.h \
    Document/SaleDocument/DocumentZALView.h\
    Goods/GoodsRemoveConfirmativeDialog.h \
    Main/MainTabItemController.h \
    Document/SaleDocument/DocumentZALManager.h \
    Document/SaleDocument/DocumentZALPolicy.h \
    Components/ButtonsList.h \
    Components/AddGroup.h \
    Tools/Help/HelpBrowser.h \
    Other/Logger.h \
    Components/Money.h \
    Other/Application/ModuleManager.h \
    Settings/OtherSettings/SettingsOutlookView.h \
    Settings/OtherSettings/SettingsOutlookController.h \
    Other/SimpleCrypt.h \
    Other/Network/HttpRequester.h \
    Other/Exceptions/NoHttpResponseException.h \
    Other/Network/NetworkHelper.h \
    Other/Exceptions/NoLicenseKeyException.h\
    Tools/Print/PrintDialogView.h \
    Tools/Print/PrintDialogController.h \
    Tools/Print/DocumentServices.h \
    Tools/Print/PrintPreviewDialog.h \
    Other/BlueBraces.h \
    Other/OtherService.h \
    Other/OtherModel.h \
    Other/Preferences/SettingsPreferencesModel.h \
    Other/Preferences/SettingsPreference.h \
    Other/Preferences/SettingsPreferencesService.h \
    Settings/GoodsSettings/SettingsPricesView.h \
    Settings/GoodsSettings/SettingsPricesController.h \
    Settings/DocumentsSettings/SettingsPriceSelectionView.h \
    Settings/DocumentsSettings/SettingsPriceSelectionController.h \
    Components/ToolButton.h \
    Main/MainTabPriceItem.h \
    Main/MainTabPriceItemController.h \
    Document/PriceDocument/PriceListView.h \
    Document/PriceDocument/PriceListController.h \
    Document/PriceDocument/PriceListModel.h \
    Document/PriceDocument/PriceList.h \
    Tools/Print/PrintSaleDocumentController.h \
    Tools/Print/PrintStoreDocumentController.h \
    Tools/Print/PrintCashDocumentController.h \
    Tools/Print/PrintPurchaseDocumentController.h \
    Tools/Print/PrintSaleDocumentManager.h \
    Tools/Print/PrintStoreDocumentManager.h \
    Tools/Print/PrintPurchaseDocumentManager.h \
    Tools/Print/HtmlStringReplacer.h \
    Tools/Print/PrintOrderDocumentController.h \
    Tools/Print/PrintOrderDocumentManager.h\
    Document/PriceDocument/PriceListService.h \
    Document/PriceDocument/PriceDocumentTVModel.h \
    Document/PriceDocument/PriceGoodSelectorController.h \
    Goods/GoodsTVStandardItemModel.h \
    Goods/GoodsFilters.h \
    Document/PriceDocument/PriceDocumentsValidator.h \
    Application.h \
    Document/PriceDocument/PriceDocumentView.h \
    Document/PriceDocument/OfferView.h \
    Document/PriceDocument/OfferController.h \
    Document/PriceDocument/OfferService.h \
    Document/PriceDocument/OfferModel.h \
    Document/PriceDocument/PriceDocumentController.h \
    Other/Application/Style.h \
    Document/CashDocument/CashDocument.h \
    Document/CashDocument/CashDocumentController.h \
    Document/CashDocument/CashDocumentModel.h \
    Document/CashDocument/CashDocumentService.h \
    Document/CashDocument/CashDocumentView.h \
    Other/Network/ForeignExchangeDownloader.h \
    Other/XmlParser.h

FORMS    +=
